import { describe, it, expect, vi, beforeEach } from 'vitest';
import { validateLicense, generateLicenseKey, isPro, resetProCache } from './license.js';

// ---------------------------------------------------------------------------
// validateLicense
// ---------------------------------------------------------------------------

describe('validateLicense', () => {
  it('accepts a key generated by generateLicenseKey', () => {
    const key = generateLicenseKey('TESTKEY1');
    expect(validateLicense(key)).toBe(true);
  });

  it('rejects a key with a tampered HMAC', () => {
    const key = generateLicenseKey('TESTKEY1');
    const tampered = key.slice(0, -4) + '0000';
    expect(validateLicense(tampered)).toBe(false);
  });

  it('rejects a key with a tampered ID', () => {
    const key = generateLicenseKey('TESTKEY1');
    const parts = key.split('-');
    parts[2] = 'XXXXXXXX';
    expect(validateLicense(parts.join('-'))).toBe(false);
  });

  it('rejects completely random strings', () => {
    expect(validateLicense('not-a-license')).toBe(false);
    expect(validateLicense('')).toBe(false);
    expect(validateLicense('MACC-PRO-XXXXXXXX-YYYYYYYYYYYYYYYYYYYYYYYY')).toBe(false);
  });

  it('is case-insensitive', () => {
    const key = generateLicenseKey('ABCD1234');
    expect(validateLicense(key.toLowerCase())).toBe(true);
  });

  it('trims surrounding whitespace', () => {
    const key = generateLicenseKey('ABCD1234');
    expect(validateLicense('  ' + key + '  ')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// generateLicenseKey
// ---------------------------------------------------------------------------

describe('generateLicenseKey', () => {
  it('produces keys matching MACC-PRO-{8}-{24} format', () => {
    const key = generateLicenseKey('TEST0001');
    expect(key).toMatch(/^MACC-PRO-[A-Z0-9]{8}-[A-F0-9]{24}$/);
  });

  it('pads short IDs to 8 chars', () => {
    const key = generateLicenseKey('AB');
    expect(key.split('-')[2]).toHaveLength(8);
  });

  it('truncates long IDs to 8 chars', () => {
    const key = generateLicenseKey('ABCDEF1234567890');
    expect(key.split('-')[2]).toHaveLength(8);
  });

  it('produces different keys for different IDs', () => {
    expect(generateLicenseKey('AAAAAAAA')).not.toBe(generateLicenseKey('BBBBBBBB'));
  });

  it('produces the same key for the same ID (deterministic)', () => {
    expect(generateLicenseKey('SAME0001')).toBe(generateLicenseKey('SAME0001'));
  });
});

// ---------------------------------------------------------------------------
// isPro
// ---------------------------------------------------------------------------

vi.mock('./config.js', () => ({
  loadConfig: vi.fn(),
}));

import { loadConfig } from './config.js';

describe('isPro', () => {
  beforeEach(() => {
    resetProCache();
    vi.mocked(loadConfig).mockReset();
  });

  it('returns true when config has a valid license key', async () => {
    const key = generateLicenseKey('PROUSER1');
    vi.mocked(loadConfig).mockResolvedValue({
      defaultModel: 'claude-sonnet-4-6',
      warningThresholdPercent: 90,
      autoPromptThresholdPercent: 98,
      compressionModel: 'claude-haiku-4-5',
      handoffOrder: [],
      licenseKey: key,
    });
    expect(await isPro()).toBe(true);
  });

  it('returns false when config has an invalid license key', async () => {
    vi.mocked(loadConfig).mockResolvedValue({
      defaultModel: 'claude-sonnet-4-6',
      warningThresholdPercent: 90,
      autoPromptThresholdPercent: 98,
      compressionModel: 'claude-haiku-4-5',
      handoffOrder: [],
      licenseKey: 'MACC-PRO-XXXXXXXX-YYYYYYYYYYYYYYYYYYYYYYYY',
    });
    expect(await isPro()).toBe(false);
  });

  it('returns false when config has no license key', async () => {
    vi.mocked(loadConfig).mockResolvedValue({
      defaultModel: 'claude-sonnet-4-6',
      warningThresholdPercent: 90,
      autoPromptThresholdPercent: 98,
      compressionModel: 'claude-haiku-4-5',
      handoffOrder: [],
    });
    expect(await isPro()).toBe(false);
  });

  it('returns false when loadConfig throws', async () => {
    vi.mocked(loadConfig).mockRejectedValue(new Error('config error'));
    expect(await isPro()).toBe(false);
  });

  it('caches the result after the first call', async () => {
    const key = generateLicenseKey('CACHE001');
    vi.mocked(loadConfig).mockResolvedValue({
      defaultModel: 'claude-sonnet-4-6',
      warningThresholdPercent: 90,
      autoPromptThresholdPercent: 98,
      compressionModel: 'claude-haiku-4-5',
      handoffOrder: [],
      licenseKey: key,
    });
    await isPro();
    await isPro();
    expect(loadConfig).toHaveBeenCalledTimes(1);
  });
});
